### ISSUE TITLE
LightNER适用于中文小样本数据集吗

### ISSUE THREAD

**Issue by haoyumei** [zjunlp/DeepKE#369]
您好，我想问下LightNER适用于中文小样本数据集吗？

**Comment by GoooDte** [comment]
适用的，我们测试过LightNER在中文数据上的表现也不错

**Comment by Tubggg** [comment]
您好，问一下为什么我在自己的中文数据集上训练LightNER过程中，进行evaluate的时候会爆显存呢？conll2003数据集就没有这个问题，我甚至将evaluate的batchsize设置为1了，还是爆显存了，显存为32G。

**Comment by haoyumei** [comment]
> 适用的，我们测试过LightNER在中文数据上的表现也不错
感谢回复！

**Comment by GoooDte** [comment]
> 您好，问一下为什么我在自己的中文数据集上训练LightNER过程中，进行evaluate的时候会爆显存呢？conll2003数据集就没有这个问题，我甚至将evaluate的batchsize设置为1了，还是爆显存了，显存为32G。

您好，请问您报显存是在哪个位置报的？

**Comment by Tubggg** [comment]
> > 您好，问一下为什么我在自己的中文数据集上训练LightNER过程中，进行evaluate的时候会爆显存呢？conll2003数据集就没有这个问题，我甚至将evaluate的batchsize设置为1了，还是爆显存了，显存为32G。
> 
> 您好，请问您报显存是在哪个位置报的？
报错如下：
Traceback (most recent call last):                                                                                                                            
  File "run.py", line 120, in main                                                                                                                            
    trainer.train()
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/module/train.py", line 88, in train
    self.evaluate(epoch)   # generator to dev.
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/module/train.py", line 105, in evaluate
    self._step(batch, mode="dev")
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/module/train.py", line 166, in _step
    pred = self.model.predict(src_tokens, src_seq_len, first)
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 420, in predict
    result = self.generate_func(tokens=None, state=prompt_state)
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 429, in greedy_generate
    token_ids = _no_beam_search_generate(decoder, tokens=tokens, state=state, max_length=max_length, max_len_a=max_len_a,
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 488, in _no_beam_search_generate
    scores = decoder.decode(tokens=token_ids, state=state)  # batch_size x vocab_size
  File "/disk1/wxl/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 206, in decode
    return self(tokens, state)[0][:, -1]
  File "/disk1/wxl/miniconda3/envs/uie/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 130, in forward
    dict = self.bart_decoder(
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/modeling_bart.py", line 1156, in forward
    layer_outputs = decoder_layer(
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/modeling_bart.py", line 448, in forward
    hidden_states, cross_attn_weights, cross_attn_present_key_value = self.encoder_attn(
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/modeling_bart.py", line 205, in forward
    value_states = torch.cat([prompt['prev_value'], value_states], dim=2)
RuntimeError: CUDA out of memory. Tried to allocate 296.00 MiB (GPU 0; 31.75 GiB total capacity; 16.12 GiB already allocated; 187.62 MiB free; 17.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Tubggg** [comment]
> > 您好，问一下为什么我在自己的中文数据集上训练LightNER过程中，进行评估的时候会爆显存呢？conll2003数据集就没有这个问题，我什至将评估的batchsize设置为1了，还是爆显存了，显存为32G。
> 
> 您好，请问您的报显存在于哪个位置报的？
报错如下：
`
Traceback (most recent call last):
File "run.py", line 120, in main
trainer.train()
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/module/train.py", line 88, in train
self.evaluate(epoch) # generator to dev.
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/module/train.py", line 105, in evaluate
self._step(batch, mode="dev")
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/module/train.py", line 166, in _step
pred = self.model.predict(src_tokens, src_seq_len, first)
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 420, in predict
result = self.generate_func(tokens=None, state=prompt_state)
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 429, in greedy_generate
token_ids = _no_beam_search_generate(decoder, tokens=tokens, state=state, max_length=max_length, max_len_a=max_len_a,
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 488, in _no_beam_search_generate
scores = decoder.decode(tokens=token_ids, state=state) # batch_size x vocab_size
File "/disk1/wxl/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 206, in decode
return self(tokens, state)[0][:, -1]
File "/disk1/wxl/miniconda3/envs/uie/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
return forward_call(*input, **kwargs)
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/model.py", line 130, in forward
dict = self.bart_decoder(
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
return forward_call(*input, **kwargs)
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/modeling_bart.py", line 1156, in forward
layer_outputs = decoder_layer(
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
return forward_call(*input, **kwargs)
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/modeling_bart.py", line 448, in forward
hidden_states, cross_attn_weights, cross_attn_present_key_value = self.encoder_attn(
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
return forward_call(*input, **kwargs)
File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/modeling_bart.py", line 205, in forward
value_states = torch.cat([prompt['prev_value'], value_states], dim=2)
RuntimeError: CUDA out of memory. Tried to allocate 296.00 MiB (GPU 0; 31.75 GiB total capacity; 16.12 GiB already allocated; 187.62 MiB free; 17.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by Tubggg** [comment]
> > 您好，问一下为什么我在自己的中文数据集上训练LightNER过程中，进行评估的时候会爆显存呢？conll2003数据集就没有这个问题，我什至将评估的batchsize设置为1了，还是爆显存了，显存为32G。
> 
> 您好，请问您的报表存在于哪个位置的报表？
报错如下：
![Uploading image.png…]()

**Comment by Tubggg** [comment]
> > 您好，问一下为什么我在自己的中文数据集上训练LightNER过程中，进行evaluate的时候会爆显存呢？conll2003数据集就没有这个问题，我甚至将evaluate的batchsize设置为1了，还是爆显存了，显存为32G。
> 
> 您好，请问您报显存是在哪个位置报的？
![Uploading LK1}S2B0CQ$M2JL`TL{[P@9.png…]()

**Comment by Tubggg** [comment]
> > 您好，问一下为什么我在自己的中文数据集上训练LightNER过程中，进行evaluate的时候会爆显存呢？conll2003数据集就没有这个问题，我甚至将evaluate的batchsize设置为1了，还是爆显存了，显存为32G。
> 
> 您好，请问您报显存是在哪个位置报的？

报错如下：
 File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/modeling_bart.py", line 205, in forward
    value_states = torch.cat([prompt['prev_value'], value_states], dim=2)

**Comment by Tubggg** [comment]
另外在加载自己的数据集的时候，在/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/module/datasets.py 的141行 assert len(word_bpes)<500报错了，我就改成了50000，会不会是因为这个导致的呢？


> > > 您好，问一下为什么我在自己的中文数据集上训练LightNER过程中，进行evaluate的时候会爆显存呢？conll2003数据集就没有这个问题，我甚至将evaluate的batchsize设置为1了，还是爆显存了，显存为32G。
> > 
> > 
> > 您好，请问您报显存是在哪个位置报的？
> 
> 报错如下： File "/disk1/miniconda3/envs/uie/lib/python3.8/site-packages/deepke/name_entity_re/few_shot/models/modeling_bart.py", line 205, in forward value_states = torch.cat([prompt['prev_value'], value_states], dim=2)

**Comment by GoooDte** [comment]
您好 可能是您的数据文本长度太大 可以尝试将50000改回500试试

**Comment by Tubggg** [comment]
> 您好 可能是您的数据文本长度太大 可以尝试将50000改回500试试

请问如果想正常训练的话，是不是需要将数据集中过长的数据进行剔除呢？

**Comment by GoooDte** [comment]
可以进行剔除，也可以选择对过长的文本进行截取

**Comment by Tubggg** [comment]
> 可以进行剔除，也可以选择对过长的文本进行截取

word_bpes变量是表示一个句子样例的长度吗

**Comment by GoooDte** [comment]
word_bpes是对句子进行分词后的token总长度

**Comment by Tubggg** [comment]
> word_bpes是对句子进行分词后的token总长度

好的，那我试试剔除，谢谢您的回答！

**Comment by Tubggg** [comment]
您好，我已经剔除了大于500的数据，并且将evaluate的batch_size设置为1了，但是还是报错显存不足

> 您好 可能是您的数据文本长度太大 可以尝试将50000改回500试试

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by Tubggg** [comment]
> 请问您的问题是否已解决？

请问您问的是我上述的问题吗？目前还没有得到解决。

**Comment by GoooDte** [comment]
建议检查一下机器上跑的是否有其他程序占用了显存，或者针对爆显存的那行代码分析一下显存变化，到底是什么导致的显存不够

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by Tubggg** [comment]
> 请问您的问题是否已解决？

应该还是训练句子过长的问题，我再想办法处理一下，谢谢您。

**Comment by haoyumei** [comment]
您好，我想请教下这个模型是需要更大内存的GPU去训练吗？我租的服务器GPU是24G,但我在conll2003数据集上训练模型时，会爆显存不足，之前训练传统的序列标注NER模型都是可以的，是因为用的是BART预训练模型吗？
